= Altinn Broker 3.0 forslag 1 (utkast)
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@messaging:messaging-solutions-to-be:
endif::[]
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 0

View dok...

.Altinn Broker 3.0 forslag 1 (utkast)
image::{imagepath}Altinn Broker 3.0 forslag 1 (utkast).png[alt=Altinn Broker 3.0 forslag 1 (utkast) image, link=https://altinn.github.io/ark/models/archi-all?view=id-3a9f8a7eb8284d66b84579f2e6ecc69e]


TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)


[cols ="1,3", options="header"]
.Elementer i view for Altinn Broker 3.0 forslag 1 (utkast)
|===

| Element
| Beskrivelse

|  Auth*?
a| Bruker standard Altinn 2 felleskomponenter​

«Sluttbruker, systembruker» / EndUserSystem User (EUS)​

SOAP: ?? %​

Basic (usr/pwd) ?%​

EC (Enterprise Certificate) 88%​

X509 Virksomhetssertifikat iht. SEID-standarden​

Problematisk å implementere, spesielt for en del Java-rammeverk.​

MP (Maskinporten Token) 0%​

POC utført i Januar 2021, men ikke prodsatt, fokus flyttet til REST-implementering.​

REST:​

BASIC​

EC​

MP (Maskinporten Token).

| Altinn Register
a| Kopier av offentlige registre som f.eks. Folkeregisteret. Fremdeles relevant?

| Broker DB
a| Liste over alle meldinger i en stor Altinn SQL Server, 

| Broker Fileshare (clustered)
a| 

| Send
a| 

| Motta
a| 

| Tilbakekall
a| 

| Hent fil mtadata
a| 

| REST
a| 

| WCF
a| WCF stands for Windows Communication Foundation. It is a framework developed by Microsoft as part of the .NET Framework to build and support service-oriented applications. WCF enables developers to create distributed applications by providing a unified programming model for building service-oriented, secure, and reliable services that can communicate across various platforms and protocols.

WCF supports multiple communication patterns, including one-way messaging, request-reply, and duplex communication, as well as multiple transport protocols such as HTTP, HTTPS, TCP, and Named Pipes. This makes WCF a versatile and powerful tool for creating services that can be consumed by clients built on various technologies.

WCF services can expose different types of endpoints, including SOAP-based endpoints and RESTful endpoints. While REST is an architectural style used for designing networked applications, WCF is a framework that can be used to implement RESTful services along with other communication patterns and protocols.

| Altinn events
a| Bjørn: Mer finkornet?

| Vurdering av begrepet "generisk meldingskomponent"
a| Teknologibinding (Microsoft/Azure) som kanskje ikke passer for alle konsumenter/mottakere? 


| Sanering
a| 

| Statistikk
a| 

| Altinn Ressursregister (RR)
a| Etterfølger etter "link service" og SRR - her for alle ressurser, ikke bare tjenester.

Se dokumentasjon på https://docs.altinn.studio/authorization/modules/resourceregistry/

Se også 2022-forslag: https://github.com/Altinn/altinn-resource-registry/issues/23. We need a new concept that can replace link service as resource bearer in Altinn 2.



| SOAP
a| 

| Altinn TTP
a| Logging; ref. https://altinn.github.io/docs/tul/tjenestetyper/felles-funksjonalitet/

| Altinn formidling 3.0
a| 

|===
****
TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)
****


