= Altinn formidling 2.0 - sekvensdiagram (påbegynt)
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@messaging:solution-altinn-formidling:
endif::[]
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 0



.Altinn formidling 2.0 - sekvensdiagram (påbegynt)
image::{imagepath}Altinn formidling 2.0 - sekvensdiagram (påbegynt).png[alt=Altinn formidling 2.0 - sekvensdiagram (påbegynt) image, link=https://altinn.github.io/ark/models/archi-all?view=id-d6362f6e46a34f1497cd6a5f0e40384c]


TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)


[cols ="1,3", options="header"]
.Elementer i view for Altinn formidling 2.0 - sekvensdiagram (påbegynt)
|===

| Element
| Beskrivelse

| Altinn 2 Formidling
a| 

| Initiate message transfer
a| Forbereder opprettelse av en formidlingstjeneste ved å sende inn nødvendig metadata, hvorpå fil kan strømmes opp .Returnerer en FileReference, en GUID som brukes videre som identifikator.
Autoriserer og oppretter metadata i databasen, FileStatus=Initialized


| Upload file
a| Strømmer opp fil for en gitt FileReference basert på opprettelse av formidlingstjeneste.
Autoriserer, strømmer opp fil til sharet, oppdaterer manifest, utfører viruskontroll og setter status til "Uploaded" for både FileStatus og RecipientStatus.
Returnerer Receipt.


| Check  if available Files
a| Lettvekt metode for mottakere som ofte må sjekke om det er nye filer tilgjengelig.
Sjekker kun i db, hopper over autorisasjons-steg. Returnerer True/false.


| Get Available Files
a| Henter en "avgivers" (Erik: du mener mottakers?) tilgjengelige formidlingstjenester med metadata og referanse for nedlasting. Inkluderer autorisasjon og henter ut liste med metadata for tilgjengelige filer.


| Download File
a| Strømmer ned fil for formidlingstjeneste basert på referanse. Autoriserer, strømmer ned fil, endrer IKKE status.

| Get receipt confirmation
a| Hent ut kvittering knyttet til filen basert på FileReference, per mottaker og totalt (alle motakere mottatt)

| Altinn 2 Formidling
a| 

| Consumert's End User System
a| 

| Provider's End User System
a| 

| Initiate message transfer
a| Forbereder opprettelse av en formidlingstjeneste ved å sende inn nødvendig metadata, hvorpå fil kan strømmes opp .Returnerer en FileReference, en GUID som brukes videre som identifikator.
Autoriserer og oppretter metadata i databasen, FileStatus=Initialized


| Avsenders prosess for  å sende melding og vedlegg
a| 

| Upload file
a| Strømmer opp fil for en gitt FileReference basert på opprettelse av formidlingstjeneste.
Autoriserer, strømmer opp fil til sharet, oppdaterer manifest, utfører viruskontroll og setter status til "Uploaded" for både FileStatus og RecipientStatus.
Returnerer Receipt.


| Provider's End User System
a| 

| Avsenders prosess for  å sende melding og vedlegg
a| 

| Sender's monitoring process (polling)
a| 

| Consumert's End User System
a| 

| Recepient's download process (polling)
a| 

| Confirm downloaded
a| Bekrefter at mottaker har lastet ned filen, hvorpå filen kan saneres dersom den møter kriteriene.
Endrer FileRecipientStatus til "Downloaded".

| Check  if available Files
a| Lettvekt metode for mottakere som ofte må sjekke om det er nye filer tilgjengelig.
Sjekker kun i db, hopper over autorisasjons-steg. Returnerer True/false.


| Get Available Files
a| Henter en "avgivers" (Erik: du mener mottakers?) tilgjengelige formidlingstjenester med metadata og referanse for nedlasting. Inkluderer autorisasjon og henter ut liste med metadata for tilgjengelige filer.


| Download File
a| Strømmer ned fil for formidlingstjeneste basert på referanse. Autoriserer, strømmer ned fil, endrer IKKE status.

| Confirm downloaded
a| Bekrefter at mottaker har lastet ned filen, hvorpå filen kan saneres dersom den møter kriteriene.
Endrer FileRecipientStatus til "Downloaded".

| Get receipt confirmation
a| Hent ut kvittering knyttet til filen basert på FileReference, per mottaker og totalt (alle motakere mottatt)

| Recepient's download process (polling)
a| 

| Sender's monitoring process (polling)
a| 

|===
****
TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)
****


