= Ikke-funksjonelle krav
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@messaging:messaging-user-needs:
endif::[]
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 0

= Juridiske forhold
* Gjeldende lovpålagte krav. Eksempel: GDPR med krav til dataminimering mv.
** Langtidslaging (arkivering)
** Dokumentasjon av etterlevelse
** Sporing av data - dataproveniens
** Krav til anonymisering, kryptering og beskyttelse av sensitive data (personvern og informasjonssikkerhet)

= Egenskaper relatert til organisatorisk samhandling
* Type forretningsprosess. Eksempler: Bilateral prosess mellom to kjente parter (herunder spørring og forhåndsavtalt, periodisk distriusjon); Tverrgående prosess mellom faste parter; Tverrgående prosess mellom dynamiske oppdagete parter
** Antall samhandlingsparter
*** En-til-en, en-til-mange, mange-til-mange, mange-til-en
** Kjente eller ukjente mottakere
** Fast eller dynamisk gruppe med samhandlingsparter
** Prosessens levetid. Relevant for feilhåndtering: Kortlevde prosesser med innebygd transaksjonssikkerhet kan tilbakerulles gjennom generelle mekanismer, f.eks. slik dette støttes av rollback i relasjonsdatabaser. Langlevde prosesser krever skreddersydde kompensasjonsaksjoner
** Roler og ansvar. Hvem skal ha ansvar for hva? Hvem sier om du får tilgang til opplysninger eller ikke?
** Støtte for samtidig versjonshåndtering og konfliktløsning
** Støtte for workflow- og godkjenningsprosesser

= Egenskaper relatert til semantisk interoperabilitet
* Støtte for felles datamodeller (core vocabularies)
* Støtte for aktuelle utvekslingsformater
* Støtte for lenking av data
* Støtte for ontologier eller semantiske standarder for bedre gjenfinning, tolkning og interoperabilitet av data
* Muligheten til å definere og utvide felles datamodeller og vocabularies basert på spesifikke bransjekrav eller domener

= Egenskaper relatert til teknisk samhandling
* Utvekslingsprotokoller
** Synkron eller asynkron kommunikasjon
** Støtte for utveklsingsprotokoller som f.eks. SOAP og REST
* Tjenestekvalitet (QoS)
** Meldingsstørrelse
*** Størrelse på enkeltvedlegg vs. samlede vedlegg?
** Leveringstid for meldinger. Mål: Mikrosekunder, millisekunder, sekunder, timer, dager
*** Garantert leveringstid vs. krav til levering







