= Introduksjon
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@messaging:messaging-introduction:
endif::[]
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 0

Altinn melding og Altinn formidling er to av produktene for meldingsutveksling som tilbys av Digdir. Disse produktene sorterer under felles produkteier, og presenteres derfor her samlet.

Altinn er for tiden i en moderniseringsprosess, der en går fra Altinn II til Altinn III. Denne prosessen forventes skal være ferdig innen juni 2025, blant annet fordi nåværende driftsavtaler da utgår. Dette innebærer betydelig innsats, da dagens Altinn-løsninger skal moderniseres og migreres til skyen.

En søker å legge opp migreringsløpet slik at det peker i "riktig" retning i forhold til et mer langsiktig løp. Det arbeides derfor med visjoner og malgsiktig strategi som grunnlag for løsningsvalfl på kort sikt.

Produktstrategien for Altinn melding og Altinn formidling henger sammen med produktstrategien for hele produktområdet for meldingsutveksling i Digdir. Det er også sammenhenger med andre produkteområder innen datadeling.






