= Felles økosystem (Kartverkets framstilling)
:wysiwig_editing: 1
ifeval::[{wysiwig_editing} == 1]
:imagepath: ../images/
endif::[]
ifeval::[{wysiwig_editing} == 0]
:imagepath: main@messaging:messaging-appendixes:
endif::[]
:experimental:
:toclevels: 4
:sectnums:
:sectnumlevels: 0

Digdirs overordnede modell med lenker til Kartverkets modeller

.Felles økosystem (Kartverkets framstilling)
image::{imagepath}Felles økosystem (Kartverkets framstilling).png[alt=Felles økosystem (Kartverkets framstilling) image, link=https://altinn.github.io/ark/models/archi-all?view=id-6bf08eff39904685bc4fef073c604960]


TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)


[cols ="1,3", options="header"]
.Elementer i view for Felles økosystem (Kartverkets framstilling)
|===

| Element
| Beskrivelse

| Modell for felles økosystem
a| Modellen viser ikke prosesser for hvordan verdiutvekslingen i økosystemet kan foregå og den viser ikke hvordan rammebetingelsene settes, ei heller prosesser for styring i felles økosystem.

| Virksomhetens verdikjeder
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Sluttbrukertjenester
a| Beskrivelse mangler på Digdirs nettsider?

| Integrerbare sluttbrukertjenestrer
a| Fremtidens tjenester må kunne integreres med andre tjenester. Sluttbrukertjenestene må kunne benyttes som en komponent inn i andre tjenester eller som en del av en tjenestekjede. Modularitet og muligheter for å kunne endre en tjeneste uten at alle de andre tjenestene den er en del av må redesignes, er en forutsetning for at en tjeneste skal kunne overleve i fremtiden. Tjenestene må bygges med standard grensesnitt da trenger ikke andre som integrerer tjenesten å vite hvordan selve tjenesten er «bygget». Sluttbruker trenger ikke vite tekniske detaljer om tjenesten, bare hvilket behov den svarer ut.

| Eksterne lenker (Integrerbare sluttbrukertjenestrer)
a| Digirs nettsider under Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Utvikling, produksjon, analyse av data
a| Beskrivelse mangler på Digdirs nettsider?

| Plattformer for tjenesteutvikling og -produksjon
a| Tjenesteutvikling og tjenesteproduksjon vil i stor grad foregå i sektorene og den enkelte virksomhet. Det vil allikevel være behov for fellesressurser for dette. Enten i form av sektorplattformer eller i form av plattformer for hele offentlig sektor. Plattformene vil være modulære, dynamiske og skalerbare og vil gjøre det enklere for mindre virksomhetene og komme i gang med sin tjenesteutvikling og tjenesteproduksjon.

| Eksterne lenker (Plattformer for tjenesteutvikling og -produksjon)
a| Digirs nettsider under Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Sammenstilling av data og datalagring
a| Sammenstilling av data (samling av data fra ulike kilder og registre til analyseformål)

https://www.digdir.no/digital-samhandling/felles-okosystem/2395#sammenstilling_av_data_og_dataanalyse

I fremtiden vil de tradisjonelle registrene kobles sammen med andre typer data fra de distribuerte datakildene. Disse vil sammenstilles for analyseformål og benyttes inn i tjenester. Det vil være behov for løsninger for sammenstilling av data, både innad i hver enkelt sektor og som fellesløsninger for alle i økosystemet. I tillegg til løsninger for sammenstilling av data vil det være behov for analyseressurser.



| Distribuerte datakilder- rådata
a| Sanntidsdata, sensordata, hendelsesdata

Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#datakilder:
I tillegg til grunndataregistrene vi har i dag, som folkeregisteret, enhetsregisteret, kontakt og reservasjonsregisteret, helseregisteret osv. vil vi i fremtiden bli mer og mer avhengige av andre typer data som sanntidsdata og sensor data. Disse dataene vil i stor grad være distribuerte. Helt vesentlig for å kunne etablere sammenhengende tjenester er hendelsesdata. Hendelsesdata beskriver hendelser som inntreffer enten i en virksomhet eller innbyggers liv, eller som følge av at data endres. Basert på hendelser vil man ha behov for tjenester. Data kan benyttes direkte inn i tjenesteproduksjon eller sammenstilles for analyseformål.

| Distribuerte datakilder og registre
a| Dataområder med masterdata

Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#datakilder:
I tillegg til grunndataregistrene vi har i dag, som folkeregisteret, enhetsregisteret, kontakt og reservasjonsregisteret, helseregisteret osv. vil vi i fremtiden bli mer og mer avhengige av andre typer data som sanntidsdata og sensor data. Disse dataene vil i stor grad være distribuerte. Helt vesentlig for å kunne etablere sammenhengende tjenester er hendelsesdata. Hendelsesdata beskriver hendelser som inntreffer enten i en virksomhet eller innbyggers liv, eller som følge av at data endres. Basert på hendelser vil man ha behov for tjenester. Data kan benyttes direkte inn i tjenesteproduksjon eller sammenstilles for analyseformål.

| Infrastruktur
a| Beskrivelse mangler på Digdirs nettsider?

| Katalogtjenester
a| Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#katalogtjenester:

Fremtidens katalogtjenester vil ikke bare ha beskrivelser av datasett, datakvalitet, API, informasjonsmodeller og begreper.

Katalogtjenestene vil inneholde tjenestekatalog og hendelses katalog. I tillegg vil vi ha katalogtjenester som støtter innebygget arkivering.

Katalogtjenestene vil ha løsninger for å søke om å få tilgang til skjermede data.

Videre vil katalogtjenesten gi tilgang til veiledninger innen områdene informasjonsforvaltning og deling av data. Det skal være enkelt å finne data, vite om dataene har god kvalitet, få tilgang til data, få veiledning i hvordan man ivaretar krav til konfidensialitet, integritet og tilgjengelighet til dataene, og ikke minst få veiledning på hvordan man ivaretar informasjonen dataene er bærere av gjennom hele informasjonens livsløp

| Tillitstjenester
a| Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#tillitstjenester:

Tillitstjenester må i fremtiden muliggjøre autentisering og autorisasjon på tvers av tjenestekjeder. Tillitstjenester må derfor støtte en distribuert arkitektur og føderering mellom ulike domener og tjenester.

| Tillitstjenester
a| Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#tillitstjenester:

Tillitstjenester må i fremtiden muliggjøre autentisering og autorisasjon på tvers av tjenestekjeder. Tillitstjenester må derfor støtte en distribuert arkitektur og føderering mellom ulike domener og tjenester.

| Datautveksling og integrasjon
a| Ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#datautveksling_og_integrasjoner:

Fremtidens tjenester vil komme med innebygget mulighet for deling av data og for sammenkobling med andre tjenester. Tjenestene vil være modulære og dynamiske. Tjenester som kobles sammen i kjeder vil i stor grad være basert på hendelser. Datautveksling og integrasjoner må derfor støtte både tjeneste- og hendelsesorientert arkitektur.

| Fagområder
a| En forutsetning for samhandling i felles økosystem er felles forståelse og felles kunnskap om hvordan samhandlingen bør foregå. I felles økosystem må vi ivareta samhandling både juridisk, organisatorisk, semantisk og teknisk. Vi må ha felles prinsipper, felles arkitekturer og benytte standarder det det kreves og der det er hensiktsmessig. Veiledninger og bestepraksisbeskrivelser innen informasjonsforvaltning, informasjonssikkerhet og arkitektur vil utarbeides gjennom deling av erfaringer og kunnskap i økosystemet.

| Informasjons-forvaltning
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Eksterne lenker
a| Digirs nettsider om informasjonsforvaltning: https://www.digdir.no/informasjonsforvaltning/informasjonsforvaltning/2113

| Informasjonssikkerhet
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Eksterne lenker
a| Digirs nettsider om Informasjonssikkerhet: https://www.digdir.no/informasjonssikkerhet/informasjonssikkerhet/882

| Arkitektur og standardisering
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Eksterne lenker
a| * Digirs nettsider om Arkitektur og standardisering: https://www.digdir.no/digital-samhandling/felles-arkitektur-og-struktur-samhandling/2150
* Digirs nettsider om standarder: https://www.digdir.no/standarder/standardar/1001

| Eksterne lenker (Fagområder)
a| Digirs nettsider under Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Ressurser for dataanalyse
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Regelverk og juridisk koordinering
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Eksterne lenker (Regelverk og juridisk koordinering)
a| * Digirs nettsider under Nasjonalt ressurssenter for deling av data: https://www.digdir.no/datadeling/nasjonalt-ressurssenter-deling-av-data/1914
* Oversikt over EU-regelverk om deling og bruk av data: https://www.digdir.no/datadeling/oversikt-over-eu-regelverk-om-deling-og-bruk-av-data/3251
* Veileder for digitaliseringsvennlig regelverk: https://www.digdir.no/datadeling/veileder-digitaliseringsvennlig-regelverk/2856


| Innovasjon og digitalisering
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Eksterne lenker Innovasjon og digitalisering)
a| Digirs nettsider under Innovasjon i offentlig sektor: https://www.digdir.no/innovasjon/innovasjon-i-offentlig-sektor/881

| Strategisk samordning og koordinering
a| Felles økosystem er dynamisk og vil være i konstant endring. Endringene skjer basert på hvordan aktørene opererer og påvirker hverandre, hvordan man løser nye behov og utfordringer, og hvordan man samhandler om dette. Samordning og koordinering er derfor viktig. Aktørene må ha en felles forståelse av reglene eller rammebetingelsene som gjelder i felles økosystem. Styring kan bare skje gjennom rammebetingelsene, og ikke av selve økosystemet. Det må for eksempel etableres gode styringsmodeller for sammenhengende tjenester, et helhetlig regelverk for sammenhengende tjenester og vi må kunne styre porteføljen av nasjonale ressurser slik at de dekker fremtidens behov.

Noen arenaer for samhandling, samordning og koordinering

* Fagarena for datadeling og informasjonsforvaltning
* NIFS – Nettverk for informasjonssikkerhet
* Skate og Skates AU
* Styringsråd
* Arkitektur og standardiseringsrådet

| Eksterne lenker (Virkemidler og finansiering) (copy)
a| Digirs nettsider under Samordning og koordinering: https://www.digdir.no/digitalisering-og-samordning/samordning-og-koordinering/1002

| Virkemidler og finansiering
a| I felles økosystem finnes det en rekke virkemidler som skal stimulere til digitalisering og innovasjon. Dette er både finansieringsmidler, verktøy og metoder for å skape endring. Både Nasjonalt ressurssenter for deling av data og tverrfaglig team for livshendelsene vil ha en viktig rolle i årene som kommer.

| Eksterne lenker (Virkemidler og finansiering)
a| Digirs nettsider under Finansiering: https://www.digdir.no/finansiering/finansiering/702

| Styring av sammenhengende  tjenester
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Eksterne lenker (Virkemidler og finansiering) (copy) (copy)
a| Digirs nettsider under Sammenhengende tjenester: https://www.digdir.no/sammenhengende-tjenester/sammenhengende-tjenester/3157

| Tjenestekjeder (hendelser, tjenester, data)
a| Fremtidens tjenester vil være sammensatt av mange enkelttjenester som kobles sammen i en helhetlig kjede. En tjenestekjede er ikke lineær og den vil kunne ha flere forgreininger og retninger. En tjenestekjede består av tjenester som er levert av ulike aktører i økosystemet.

Tjenestekjeder kan være forhåndsdefinert eller orkestrert for å svare ut et behov som følger et bestemt mønster, men det vil også være mer dynamiske tjenestekjeder som tilpasses den enkelte brukers behov basert på hendelser og endringer som oppstår i innbyggerens liv.

Vi kan beskrive sammenhengende tjenester som hendelser, tjenester og data. En hendelse kan utløse behov for en tjeneste. Tjenesten bruker og fører til endringer i data. Endring i data fører til en ny hendelse som igjen kan utløse behov for tjenester. Da snakker vi om en kjede av tjenester. Hvis tjenestekjeden fremstår sammenhengende for brukeren snakker vi om sammenhengende tjenester.

Tjenestekjedene vil kunne baseres på analyse av data, og det vil være mulig at tjenestene predikerer mulige utfall basert på valg en innbygger tar.

Tjenester vil komme med innebygget mulighet for deling av data, de vil komme med innebygget arkivering, og de vil komme med mulighet for at de kan kobles sammen med andre tjenester og danne tjenestekjeder.

Slik lager vi sammenhengende tjenester:

<<Figur>> ref. https://www.digdir.no/digital-samhandling/felles-okosystem/2395#tjenestekjeder

| Ledd i tjenestekjede
a| 

| Eksterne lenker (Tjenestekjeder )
a| Digirs nettsider under Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Aktører
a| Aktørene som utvikler og tilbyr tjenester i felles økosystem er kommunal-, statlig-, privat- og frivillig sektor. Alle disse aktørene operer i flere økosystem.

I tillegg til å være en del av felles økosystem har aktørene egne økosystem innen hver sektor og hver virksomhet.

For å lykkes med sammenhengende tjenester må det etableres et samspill og en harmonisering mellom de ulike sektor-økosystemene. Dette samspillet vil skje i felles økosystem. Aktørene må samhandle, dele kunnskap og etablere felles forståelse. De må dele data og sikre kvalitet i informasjon, og de må jobbe sammen om å levere gode tjenester blant annet ved bruk av delte ressurser.

Innbyggeren vil interagere i og med mange økosystem når det inntreffer en livshendelse eller når innbygger har behov for en tjeneste fra det offentlige.

Skal vi skape gode digitale tjenester for innbygger, må aktørene i felles økosystem finne gode samhandlingsformer og jobbe for å fjerne hindringer både innen det juridiske, organisatoriske, semantisk og tekniske området.

Felles økosystem er bare en liten del av hver enkelt aktørs økosystem; se figur under https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167.

| Statlig sektor
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Privat sektor
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Frivillig sektor
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Kommunal sektor
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Innbygger
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Regjering, Departementer og KS
a| Beskrivelse mangler under https://www.digdir.no/digital-samhandling/felles-okosystem/2395

| Eksterne lenker (Aktører)
a| Digirs nettsider under Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

| Eksterne lenker
a| Digirs nettsider om
* Felles økosysem: https://www.digdir.no/digital-samhandling/felles-okosystem/4165
* Modell for felles økosystem: https://www.digdir.no/digital-samhandling/modell-felles-okosystem/4167

|===
****
TIP: Gå tilbake til standardvisning ved å klikke 'tilbake' (eller lukk dette vinduet om det er nytt)
****


